#' Utility functions for calculating Pareto optimality
#'
#' Plots Pareto optimality between two traits or landscapes Z values across morphospace.
#'
#' @param x Output from calc_lscps_Pareto
#' @param n1 First variable to plot
#' @param n2 Second variable to plot
#' @return A series of ggplot graphs, generated by a series of helper functions. These can be accessed and viewed individually, or plotted all at once using the 'patchwork' package

plot_lscp_Pareto <- function(x,n1=NULL,n2=NULL){
  if (!inherits(x,'PO_List')){
    ParOpt <- calc_lscp_Pareto(x,n1,n2)
  } else {
    ParOpt <- x
    }
  
  plt1 <- plot_ggtrade(ParOpt)
  plt2 <- plot_ggPareto(ParOpt)
  
  return(list(plt1,plt2))
}

#' plot_ggsurf
#'
#' Helper function - plots specific performance surface or landscape. Data
#' must be in tabular format. Grid is color-coded according to trait value
#' or Z score.
#'
#' @param x PO_List object, result of calc_lscp_Pareto. Alternatively, a dataframe or tibble containing trait values
#' @param n1 Name of the trait variable or group landscape being plotted
#'
#' @return A ggplot object

plot_ggsurf <- function(x,n1=NULL){
  if (inherits(x,'PO_List')){
    
    dfg <- x$grp_Wprimes[[n1]]$Wprime$Wprime$grid
    names(dfg)[names(dfg) == "Z"] <- n1 
    
    dfd <- x$grp_Wprimes[[n1]]$Wprime$Wprime$new_data
  
  p1 <- ggplot(dfg,aes(x=.data$x,y=.data$y))+
    geom_raster(aes(fill=get(n1)))+
    geom_point(data=dfd,aes(x=.data$x,y=.data$y))+
    scale_fill_viridis_c(name=n1)+
    scale_x_continuous(expand=c(0,0))+
    scale_y_continuous(expand=c(0,0))+
    theme_classic()
  
  return(p1)
  
  } else if (inherits(x,"kriged_surfaces")) {
    
    y <- x$dataframes$grid
    dfg <- x$dataframes$grid
    dfd <- x$dataframes$new_data
    
    p1 <- ggplot(dfg,aes(x=.data$x,y=.data$y))+
      geom_raster(aes(fill=get(n1)))+
      geom_point(data=dfd,aes(x=.data$x,y=.data$y))+
      scale_fill_viridis_c(name=n1)+
      scale_x_continuous(expand=c(0,0))+
      scale_y_continuous(expand=c(0,0))+ 
      theme_classic()
    
    return(p1)
  }
}

#' plot_ggtrade
#'
#' Helper function - plots trade-offs between different traits or
#' landscape Z scores, as an x-y scatterplot. Points are color coded
#' according to Pareto optimality Ri score.
#'
#' @param x PO_List object, result of calc_lscp_Pareto. Alternatively, a dataframe or tibble containing trait values
#' @param n1 First variable to plot
#' @param n2 Second variable to plot
#'
#' @return A ggplot object

plot_ggtrade <- function(x,n1=NULL,n2=NULL){
  if (!inherits(x,'PO_List')){
    ParOpt <- calc_lscp_Pareto(x,n1,n2)
  } else {
    ParOpt <- x
  }
  
  df <- ParOpt$grid
  v1 <- ParOpt$names[1]
  v2 <- ParOpt$names[2]
  ParFront <- df[df$Ri == max(df$Ri),]

  ggplot(df,
         aes(x=!!sym(v1),y=!!sym(v2),color=.data$Ri))+
    #geom_tile(aes(fill=value))+
    geom_point(aes(color=.data$Ri))+
    # geom_contour_tanaka(aes(z=.level))+
    scale_color_viridis_c(option="magma",direction=1,
                          name = "Pareto\nOptimality")+
    geom_step(data=ParFront,size=1.5,color='black')+
    theme_classic()
}

#' plot_ggPareto
#'
#' Helper function - plots Pareto optimality Ri across the grid.
#' Contours are color coded according Ri score. Additionally,
#' the Pareto front is drawn using geom_smooth on the subset of
#' points whose Ri == maximum Ri
#' @param x PO_List object, result of calc_lscp_Pareto. Alternatively, a dataframe or tibble containing trait values
#' @param n1 First variable to plot
#' @param n2 Second variable to plot
#'
#' @return A ggplot object

plot_ggPareto <- function(x,n1=NULL,n2=NULL){
  if (!inherits(x,'PO_List')){
    ParOpt <- calc_lscp_Pareto(x,n1,n2)
  } else {
    ParOpt <- x
  }
  
  df <- ParOpt$grid
  ParFront <- df[df$Ri == max(df$Ri),]
  
  ggplot(df,aes(x=.data$x,y=.data$y))+
    #geom_tile(aes(fill=value))+
    geom_raster(aes(fill=.data$Ri))+
    geom_smooth(data=ParFront,
                color='black',se = FALSE)+
    # geom_contour_tanaka(aes(z=.level))+
    scale_fill_viridis_c(option="magma",direction=1,
                         name = "Pareto\nOptimality")+
    scale_x_continuous(expand=c(0,0))+
    scale_y_continuous(expand=c(0,0))+
    theme_classic()
}